/* DELETA BANCO DE DADOS
USE master
GO
DROP DATABASE ORDEMSERVICO2
*/
CREATE DATABASE ORDEMSERVICO2
GO
USE ORDEMSERVICO2
GO

-- tabela de veículo
CREATE TABLE CLIENTE(
	IDCLIENTE INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	ENDERECO VARCHAR(45),
	CPF CHAR(11),
	CNPJ CHAR(15),
    CONSTRAINT UNIQUE_CNPJ_CPF_CLIENTE UNIQUE (CNPJ, CPF)
)

-- tabela de equipe
CREATE TABLE EQUIPE(
	IDEQUIPE INT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(45)
)

-- tabela de mecanico
CREATE TABLE MECANICO (
	IDMECANICO INT IDENTITY(1,1) PRIMARY KEY,
	IDMEQUIPE INT NOT NULL,
	NOME NVARCHAR(100),
	ENDERECO NVARCHAR(255),
	ESPECIALIDADE NVARCHAR(50),
	CONSTRAINT FK_MECANICO_EQUIPE FOREIGN KEY (IDMEQUIPE) REFERENCES EQUIPE (IDEQUIPE)
)


-- tabela de mão de obra
CREATE TABLE MAODEOBRA(
	IDMAODEOBRA INT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(45) NOT NULL,
	VALOR FLOAT DEFAULT 30
)

-- tabela de veículo
CREATE TABLE VEICULO(
	IDVEICULO INT IDENTITY(1,1),
	IDVCLIENTE INT,
	MARCA VARCHAR(15),
	MODELO VARCHAR(25),
	CONSTRAINT FK_VEICULO_CLIENT FOREIGN KEY (IDVCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
	CONSTRAINT PK_VEICULOS PRIMARY KEY (IDVEICULO, IDVCLIENTE)
)


-- tabela de peças do veículo
CREATE TABLE PECASVEICULO(
	IDPECA INT IDENTITY(1,1) PRIMARY KEY,
	VALOR FLOAT NOT NULL,
	DESCRICAO VARCHAR(45) NOT NULL
)

-- tabela de servicos
CREATE TABLE SERVICO(
	IDSERVICO INT IDENTITY(1,1) PRIMARY KEY,
	IDSMAODEOBRA INT,
	DESCRICAO VARCHAR(45) NOT NULL,
	CONSTRAINT FK_SERVICO_MAODEOBRA FOREIGN KEY (IDSMAODEOBRA) REFERENCES MAODEOBRA (IDMAODEOBRA)
)

-- tabela de ordem de serviço
CREATE TABLE ORDEMSERVICO(
	IDORDEMSERVICO INT IDENTITY(1,1) PRIMARY KEY,
	NUMERO INT NOT NULL,
	DATAEMISSAO DATETIME,
	VALOR FLOAT NOT NULL,
	STATUS VARCHAR(45) DEFAULT 'Cadastrado',
	DATACONCLUSAO DATETIME,
	CONSTRAINT CHK_ORDEMSERVICO CHECK (STATUS IN('Cadastrado', 'Em Processamento', 'Executando', 'Finalizado'))
)

-- tabela de cliente autoriza execução de serviços
CREATE TABLE CLIENTESERVICOS(
	IDCSCLIENTE INT,
	IDCSORDEMSERVICO INT,
	CONSTRAINT FK_CLIENTESERVICOS_CLIENTE FOREIGN KEY (IDCSCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
	CONSTRAINT FK_CLIENTESERVICOS_ORDEMSERVICO FOREIGN KEY (IDCSORDEMSERVICO) REFERENCES ORDEMSERVICO (IDORDEMSERVICO)
)

-- tabela de Ordem Serviço possui peças de veículo
CREATE TABLE PECASSERVICOS(
	IDPSPECA INT,
	IDPSORDEMSERVICO INT,
	CONSTRAINT FK_PECASSERVICOS_PECAS FOREIGN KEY (IDPSPECA) REFERENCES PECASVEICULO (IDPECA),
	CONSTRAINT FK_PECASSERVICOS_ORDEMSERVICO FOREIGN KEY (IDPSORDEMSERVICO) REFERENCES ORDEMSERVICO (IDORDEMSERVICO)
)

-- tabela de Relação de Serviço e OS
CREATE TABLE SERVICOORDEMSERVICO(
	IDSOSORDEMSERVICO INT,
	IDSOSSERVICO INT,
	CONSTRAINT FK_SERVICOORDEMSERVICO_ORDEMSERVICO FOREIGN KEY (IDSOSORDEMSERVICO) REFERENCES ORDEMSERVICO (IDORDEMSERVICO),
	CONSTRAINT FK_SERVICOORDEMSERVICO_SERVICO FOREIGN KEY (IDSOSSERVICO) REFERENCES SERVICO (IDSERVICO),
)

-- tabela de Equipe Avalia/Executa Ordem de Serviço
CREATE TABLE EQUIPEORDEMSERVICO(
	IDEOSEQUIPE INT,
	IDEOSORDEMSERVICO INT,
	CONSTRAINT FK_EQUIPEORDEMSERVICO_ORDEMSERVICO FOREIGN KEY (IDEOSORDEMSERVICO) REFERENCES ORDEMSERVICO (IDORDEMSERVICO),
	CONSTRAINT FK_EQUIPEORDEMSERVICO_EQUIPE FOREIGN KEY (IDEOSEQUIPE) REFERENCES EQUIPE (IDEQUIPE),
)